const seedAssets = [
 {id:'number 1',category:'LIFTING',equipment:'Carbon spreader bar',manufacturer:'',tag:'Numbered on ends',wll:'',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'2027-01-01',status:'ACTIVE',location:'Main Store',availability:'AVAILABLE'},
 {id:'37 orange dot',category:'FITTING / ANCHOR',equipment:'Doughty Petzl eyes',manufacturer:'',tag:'Orange Mark',wll:'15–25 kN',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'2027-01-01',status:'ACTIVE',location:'Main Store',availability:'AVAILABLE'},
 {id:'FIGURE8/0001',category:'DESCENDER',equipment:'Figure 8',manufacturer:'DMM',tag:'DMM',wll:'25 kN',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'2027-01-01',status:'ACTIVE',location:'Main Store',availability:'AVAILABLE'},
 {id:'19B0178877613',category:'DESCENDER',equipment:'Petzl Square 8',manufacturer:'PETZL',tag:'',wll:'25 kN',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'2027-01-01',status:'ACTIVE',location:'Main Store',availability:'AVAILABLE'},
 {id:'FCC ID:Q0QBLE112',category:'LOAD TESTING',equipment:'Load cell',manufacturer:'ROCK EXOTICA',tag:'',wll:'',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'2027-01-01',status:'ACTIVE',location:'Main Store',availability:'AVAILABLE'},
 {id:'1010405',category:'LIFTING',equipment:'Yellow 800kg lever hoist',manufacturer:'',tag:'',wll:'800 kg',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'2027-01-01',status:'ACTIVE',location:'Main Store',availability:'AVAILABLE'},
 {id:'320556',category:'LIFTING',equipment:'Black Ace 3/4 lever hoist',manufacturer:'',tag:'',wll:'',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'',status:'INACTIVE',location:'Quarantine',availability:'AVAILABLE'},
 {id:'BATCH 4249VS X 36',category:'CONNECTOR',equipment:'Karabiner',manufacturer:'',tag:'',wll:'25 kN',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'2027-01-01',status:'ACTIVE',location:'Main Store',availability:'AVAILABLE'},
 {id:'180340104',category:'CONNECTOR',equipment:'Karabiner DMM 4kN',manufacturer:'DMM',tag:'DMM 4kN',wll:'4 kN',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'2027-01-01',status:'ACTIVE',location:'Main Store',availability:'CHECKED OUT',project:'Stage 4 Flying Rig',holder:'Rigging Team A'},
 {id:'14009J0582',category:'CONNECTOR',equipment:'Karabiner Petzl Oxan',manufacturer:'PETZL',tag:'',wll:'38 kN',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'2027-01-01',status:'ACTIVE',location:'Main Store',availability:'AVAILABLE'},
 {id:'24F0573299364',category:'CONNECTOR',equipment:'Karabiner Petzl Oxan 2022 Edition',manufacturer:'PETZL',tag:'',wll:'38 kN',enteredService:'Before 2026',interval:'1 Yr',lastInspection:'2026-01-01',inspectedBy:'BICKERS LTD',nextInspection:'2027-01-01',status:'ACTIVE',location:'Main Store',availability:'AVAILABLE'}
];

const state = {
 view:'dashboard', assets:load('asi_assets',seedAssets), transactions:load('asi_tx',[]), projects:load('asi_projects',[{name:'Stage 4 Flying Rig',production:'Current production',location:'Stage 4',status:'ACTIVE'}]),
 search:'', category:'ALL', status:'ALL', availability:'ALL', modal:null, toast:null, sheetUrl:localStorage.getItem('asi_sheet_url')||'', mobile:false
};
function load(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
function save(){localStorage.setItem('asi_assets',JSON.stringify(state.assets));localStorage.setItem('asi_tx',JSON.stringify(state.transactions));localStorage.setItem('asi_projects',JSON.stringify(state.projects))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function today(){return new Date().toISOString().slice(0,10)}
function inspectionState(a){if(!a.nextInspection)return 'none';const d=new Date(a.nextInspection+'T00:00:00'),now=new Date(),soon=new Date();soon.setDate(now.getDate()+60);if(d<new Date(now.toDateString()))return 'overdue';if(d<=soon)return 'due';return 'current'}
function icon(name){return ({dashboard:'▦',inventory:'◫',inspections:'✓',checkout:'⇄',projects:'▣',sync:'↻'}[name]||'•')}
function navLabel(v){return ({dashboard:'Dashboard',inventory:'Inventory',inspections:'Inspections',checkout:'Check in / out',projects:'Projects & kits',sync:'Google Sheets sync'}[v])}
function render(){document.getElementById('app').innerHTML=`<div class="shell">
<aside class="sidebar ${state.mobile?'open':''}"><div class="brand"><img src="logo.svg" alt="AllStunts Inc"><small>Rigging Inventory</small></div><nav class="nav">${['dashboard','inventory','inspections','checkout','projects','sync'].map(v=>`<button class="${state.view===v?'active':''}" onclick="go('${v}')"><span class="icon">${icon(v)}</span>${navLabel(v)}</button>`).join('')}</nav><div class="sidefoot"><strong>Local field mode</strong><br>Changes are saved on this device. Connect a published Google Sheet to refresh the master register.</div></aside>
<main class="main"><header class="topbar"><div style="display:flex;align-items:center;gap:10px"><button class="btn ghost mobile-menu" onclick="toggleMenu()">☰</button><h1>${navLabel(state.view)}</h1></div><div class="top-actions"><button class="btn desktop-only" onclick="exportCsv()">Export CSV</button><button class="btn primary" onclick="openAsset()">+ Add asset</button></div></header><section class="content">${view()}</section></main></div>${modal()}${state.toast?`<div class="toast ${state.toast.bad?'bad':''}">${esc(state.toast.msg)}</div>`:''}`}
function go(v){state.view=v;state.mobile=false;render()} window.go=go;
window.toggleMenu=()=>{state.mobile=!state.mobile;render()};
}
function view(){return ({dashboard:dashboard,inventory:inventory,inspections:inspections,checkout:checkout,projects:projects,sync:syncView}[state.view]||dashboard)()}
function dashboard(){const active=state.assets.filter(a=>a.status==='ACTIVE').length,out=state.assets.filter(a=>a.availability==='CHECKED OUT').length,over=state.assets.filter(a=>inspectionState(a)==='overdue').length,due=state.assets.filter(a=>inspectionState(a)==='due').length;const cats=countBy(state.assets,'category');return `<div class="hero card"><div><div class="kicker">AllStunts Inc.</div><h2>Rigging asset control</h2><p>Live availability, inspection status and movement history for safety-critical equipment.</p></div><button class="btn primary" onclick="go('checkout')">Check kit in / out</button></div>
<div class="grid stats"><div class="card stat ok"><div class="label">Active assets</div><div class="value">${active}</div><div class="hint">${state.assets.length} total records</div></div><div class="card stat warn"><div class="label">Checked out</div><div class="value">${out}</div><div class="hint">Across active projects</div></div><div class="card stat bad"><div class="label">Overdue inspections</div><div class="value">${over}</div><div class="hint">Requires immediate review</div></div><div class="card stat warn"><div class="label">Due within 60 days</div><div class="value">${due}</div><div class="hint">Plan with Bickers / inspector</div></div></div>
<div class="grid split"><div class="card panel"><h2>Inspection attention</h2>${attentionList()}</div><div class="card panel"><h2>Inventory by category</h2>${Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`<div class="category-row"><span>${esc(k||'Uncategorised')}</span><div class="bar"><i style="width:${Math.max(5,v/state.assets.length*100)}%"></i></div><b>${v}</b></div>`).join('')}</div></div>`}
function attentionList(){const items=state.assets.filter(a=>['overdue','due'].includes(inspectionState(a))).sort((a,b)=>(a.nextInspection||'').localeCompare(b.nextInspection||'')).slice(0,7);if(!items.length)return `<div class="empty">No inspections currently due.</div>`;return `<div class="alert-list">${items.map(a=>`<div class="alert" onclick="showAsset('${enc(a.id)}')"><strong>${esc(a.equipment)} · ${esc(a.id)}</strong><span>${inspectionState(a)==='overdue'?'Overdue':'Due soon'} — ${fmtDate(a.nextInspection)}</span></div>`).join('')}</div>`}
function filteredAssets(){return state.assets.filter(a=>(state.category==='ALL'||a.category===state.category)&&(state.status==='ALL'||a.status===state.status)&&(state.availability==='ALL'||a.availability===state.availability)&&[a.id,a.equipment,a.manufacturer,a.tag,a.location,a.project].join(' ').toLowerCase().includes(state.search.toLowerCase()))}
function inventory(){const cats=[...new Set(state.assets.map(a=>a.category).filter(Boolean))].sort();return `<div class="card panel"><div class="toolbar"><div class="search"><input value="${esc(state.search)}" oninput="setFilter('search',this.value)" placeholder="Search ID, equipment, manufacturer, location…"></div><div class="filters"><select onchange="setFilter('category',this.value)"><option>ALL</option>${cats.map(c=>`<option ${state.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select><select onchange="setFilter('status',this.value)">${['ALL','ACTIVE','INACTIVE'].map(x=>`<option ${state.status===x?'selected':''}>${x}</option>`).join('')}</select><select onchange="setFilter('availability',this.value)">${['ALL','AVAILABLE','CHECKED OUT'].map(x=>`<option ${state.availability===x?'selected':''}>${x}</option>`).join('')}</select></div></div>${assetTable(filteredAssets())}</div>`}
function assetTable(rows){if(!rows.length)return `<div class="empty">No matching assets.</div>`;return `<div class="table-wrap"><table><thead><tr><th>Asset ID / SN</th><th>Category</th><th>Equipment</th><th>Manufacturer</th><th>WLL / SWL</th><th>Next inspection</th><th>Status</th><th>Availability</th></tr></thead><tbody>${rows.map(a=>`<tr onclick="showAsset('${enc(a.id)}')"><td><strong>${esc(a.id)}</strong></td><td>${esc(a.category)}</td><td>${esc(a.equipment)}</td><td>${esc(a.manufacturer||'—')}</td><td>${esc(a.wll||'—')}</td><td>${fmtDate(a.nextInspection)}</td><td><span class="pill ${a.status.toLowerCase()}">${esc(a.status)}</span></td><td><span class="pill ${a.availability==='CHECKED OUT'?'out':'available'}">${esc(a.availability)}</span></td></tr>`).join('')}</tbody></table></div>`}
function inspections(){const rows=[...state.assets].sort((a,b)=>(a.nextInspection||'9999').localeCompare(b.nextInspection||'9999'));return `<div class="card panel"><div class="toolbar"><div><h2 style="margin:0">Inspection register</h2><span class="muted" style="font-size:12px">Annual and scheduled inspection tracking</span></div><button class="btn" style="margin-left:auto" onclick="exportInspectionCsv()">Export inspection list</button></div><div class="table-wrap"><table><thead><tr><th>Asset</th><th>Equipment</th><th>Last inspection</th><th>Inspector</th><th>Interval</th><th>Next inspection</th><th>Condition</th></tr></thead><tbody>${rows.map(a=>{const s=inspectionState(a);return `<tr onclick="showAsset('${enc(a.id)}')"><td>${esc(a.id)}</td><td>${esc(a.equipment)}</td><td>${fmtDate(a.lastInspection)}</td><td>${esc(a.inspectedBy||'—')}</td><td>${esc(a.interval||'—')}</td><td>${fmtDate(a.nextInspection)}</td><td><span class="pill ${s==='current'?'active':s}">${s==='none'?'NOT SET':s.toUpperCase()}</span></td></tr>`}).join('')}</tbody></table></div></div>`}
function checkout(){const checked=state.assets.filter(a=>a.availability==='CHECKED OUT');return `<div class="grid split"><div class="card panel"><h2>Quick movement</h2><div class="form-grid"><div class="field full"><label>Scan or enter asset ID</label><input id="moveId" placeholder="Asset barcode / serial number"></div><div class="field"><label>Action</label><select id="moveAction"><option>CHECK OUT</option><option>CHECK IN</option></select></div><div class="field"><label>Person / department</label><input id="moveHolder" placeholder="e.g. Stunt rigging team"></div><div class="field"><label>Production / project</label><input id="moveProject" list="projectList" placeholder="Production or project"><datalist id="projectList">${state.projects.map(p=>`<option value="${esc(p.name)}">`).join('')}</datalist></div><div class="field"><label>Location</label><input id="moveLocation" placeholder="Stage, unit base, store…"></div><div class="field full"><label>Notes</label><textarea id="moveNotes" rows="3"></textarea></div></div><div style="margin-top:14px"><button class="btn primary" onclick="processMove()">Record movement</button></div></div><div class="card panel"><h2>Currently checked out (${checked.length})</h2>${checked.length?`<div class="alert-list">${checked.slice(0,12).map(a=>`<div class="alert" onclick="showAsset('${enc(a.id)}')"><strong>${esc(a.equipment)} · ${esc(a.id)}</strong><span>${esc(a.project||'No project')} · ${esc(a.holder||'Unassigned')}</span></div>`).join('')}</div>`:`<div class="empty">Everything is checked in.</div>`}</div></div><div class="card panel" style="margin-top:18px"><h2>Movement history</h2>${transactionTable()}</div>`}
function transactionTable(){if(!state.transactions.length)return `<div class="empty">No movements recorded yet.</div>`;return `<div class="table-wrap"><table><thead><tr><th>Date / time</th><th>Asset</th><th>Action</th><th>Holder</th><th>Project</th><th>Location</th><th>Notes</th></tr></thead><tbody>${state.transactions.slice().reverse().map(t=>`<tr><td>${esc(new Date(t.time).toLocaleString('en-GB'))}</td><td>${esc(t.assetId)}</td><td>${esc(t.action)}</td><td>${esc(t.holder||'—')}</td><td>${esc(t.project||'—')}</td><td>${esc(t.location||'—')}</td><td>${esc(t.notes||'—')}</td></tr>`).join('')}</tbody></table></div>`}
function projects(){return `<div class="toolbar"><button class="btn primary" onclick="openProject()">+ New project</button></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(280px,1fr))">${state.projects.map(p=>{const n=state.assets.filter(a=>a.project===p.name&&a.availability==='CHECKED OUT').length;return `<div class="card panel"><div class="kicker">${esc(p.status)}</div><h2>${esc(p.name)}</h2><p class="muted">${esc(p.production||'')} ${p.location?'· '+esc(p.location):''}</p><div class="stat" style="padding:8px 0 0"><div class="value" style="font-size:26px">${n}</div><div class="hint">assets assigned</div></div></div>`}).join('')}</div>`}
function syncView(){return `<div class="card panel"><h2>Connect the live Google Sheet</h2><div class="notice">For a browser-only version, the sheet must be published as CSV or exposed through a Google Apps Script web endpoint. A normal private edit URL cannot be read directly by this app.</div><div class="field" style="margin-top:18px"><label>Published CSV or Apps Script endpoint</label><div class="sync-box"><input id="sheetUrl" value="${esc(state.sheetUrl)}" placeholder="https://docs.google.com/spreadsheets/d/.../pub?output=csv"><button class="btn primary" onclick="syncSheet()">Sync now</button></div></div><div class="toolbar" style="margin-top:16px"><label class="btn"><input type="file" accept=".csv,text/csv" style="display:none" onchange="importCsvFile(this.files[0])">Import CSV file</label><button class="btn danger" onclick="resetDemo()">Reset local data</button></div><h2 style="margin-top:28px">Expected column headings</h2><p class="muted">The importer recognises your register headings, including ASSET ID (Barcode/SN), CATERGORY / CATEGORY, EQUIPMENT, MANUFACTURER, COMPANY TAG / MARKING, SWL / WLL, ENTERED SERVICE, INSPECTION INTERVAL, LAST INSPECTION, INSPECTED BY, NEXT INSPECTION and CURRENT STATUS.</p></div>`}
function modal(){if(!state.modal)return '';if(state.modal.type==='assetDetail'){const a=state.modal.asset;return `<div class="modal-backdrop" onclick="backdrop(event)"><div class="modal"><div class="modal-head"><div class="asset-title"><div class="asset-badge">${esc((a.category||'A').slice(0,2))}</div><div><div class="kicker">${esc(a.category)}</div><h2>${esc(a.equipment)}</h2></div></div><button class="btn ghost" onclick="closeModal()">✕</button></div><div class="modal-body"><div class="detail-grid">${detail('Asset ID / serial',a.id)}${detail('Manufacturer',a.manufacturer)}${detail('WLL / SWL',a.wll)}${detail('Company tag / marking',a.tag)}${detail('Current status',a.status)}${detail('Availability',a.availability)}${detail('Last inspection',fmtDate(a.lastInspection))}${detail('Inspected by',a.inspectedBy)}${detail('Next inspection',fmtDate(a.nextInspection))}${detail('Location',a.location)}${detail('Project',a.project)}${detail('Holder',a.holder)}</div></div><div class="modal-foot"><button class="btn danger" onclick="deleteAsset('${enc(a.id)}')">Delete</button><button class="btn" onclick="openAsset('${enc(a.id)}')">Edit</button><button class="btn primary" onclick="quickToggle('${enc(a.id)}')">${a.availability==='CHECKED OUT'?'Check in':'Check out'}</button></div></div></div>`}
if(state.modal.type==='assetForm'){const a=state.modal.asset||{};return `<div class="modal-backdrop" onclick="backdrop(event)"><div class="modal"><div class="modal-head"><h2>${state.modal.edit?'Edit asset':'Add asset'}</h2><button class="btn ghost" onclick="closeModal()">✕</button></div><div class="modal-body"><div class="form-grid">${input('Asset ID / barcode / serial','f_id',a.id,true)}${input('Category','f_category',a.category)}${input('Equipment','f_equipment',a.equipment,true)}${input('Manufacturer','f_manufacturer',a.manufacturer)}${input('Company tag / marking','f_tag',a.tag)}${input('SWL / WLL','f_wll',a.wll)}${input('Entered service','f_entered',a.enteredService)}${input('Inspection interval','f_interval',a.interval||'1 Yr')}${input('Last inspection','f_last',a.lastInspection,false,'date')}${input('Inspected by','f_inspector',a.inspectedBy)}${input('Next inspection','f_next',a.nextInspection,false,'date')}${selectField('Current status','f_status',['ACTIVE','INACTIVE'],a.status||'ACTIVE')}${input('Location','f_location',a.location)}${selectField('Availability','f_availability',['AVAILABLE','CHECKED OUT'],a.availability||'AVAILABLE')}</div></div><div class="modal-foot"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveAsset('${state.modal.edit?enc(state.modal.originalId):''}')">Save asset</button></div></div></div>`}
if(state.modal.type==='project'){return `<div class="modal-backdrop" onclick="backdrop(event)"><div class="modal"><div class="modal-head"><h2>New project</h2><button class="btn ghost" onclick="closeModal()">✕</button></div><div class="modal-body"><div class="form-grid">${input('Project name','p_name','',true)}${input('Production','p_production','')}${input('Location','p_location','')}${selectField('Status','p_status',['ACTIVE','CLOSED'],'ACTIVE')}</div></div><div class="modal-foot"><button class="btn primary" onclick="saveProject()">Create project</button></div></div></div>`}return ''}
function detail(l,v){return `<div class="detail"><small>${l}</small><strong>${esc(v||'—')}</strong></div>`}function input(l,id,v='',req=false,type='text'){return `<div class="field"><label>${l}${req?' *':''}</label><input id="${id}" type="${type}" value="${esc(v||'')}"></div>`}function selectField(l,id,opts,val){return `<div class="field"><label>${l}</label><select id="${id}">${opts.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('')}</select></div>`}
function setFilter(k,v){state[k]=v;render()} window.setFilter=setFilter;
function enc(v){return encodeURIComponent(v)} function find(id){return state.assets.find(a=>a.id===decodeURIComponent(id))}
function fmtDate(v){if(!v)return '—';const d=new Date(v+'T00:00:00');return isNaN(d)?esc(v):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function countBy(arr,k){return arr.reduce((o,x)=>(o[x[k]||'Uncategorised']=(o[x[k]||'Uncategorised']||0)+1,o),{})}
function showAsset(id){const a=find(id);if(a){state.modal={type:'assetDetail',asset:a};render()}}window.showAsset=showAsset;
function openAsset(id){const a=id?find(id):null;state.modal={type:'assetForm',asset:a?{...a}:{},edit:!!a,originalId:a?.id};render()}window.openAsset=openAsset;
function closeModal(){state.modal=null;render()}window.closeModal=closeModal;window.backdrop=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()};
function val(id){return document.getElementById(id)?.value.trim()||''}
function saveAsset(original){const a={id:val('f_id'),category:val('f_category').toUpperCase(),equipment:val('f_equipment'),manufacturer:val('f_manufacturer'),tag:val('f_tag'),wll:val('f_wll'),enteredService:val('f_entered'),interval:val('f_interval'),lastInspection:val('f_last'),inspectedBy:val('f_inspector'),nextInspection:val('f_next'),status:val('f_status'),location:val('f_location'),availability:val('f_availability')};if(!a.id||!a.equipment)return toast('Asset ID and equipment are required',true);const orig=original?decodeURIComponent(original):'';if(state.assets.some(x=>x.id===a.id&&x.id!==orig))return toast('That asset ID already exists',true);if(orig){const i=state.assets.findIndex(x=>x.id===orig);a.project=state.assets[i].project||'';a.holder=state.assets[i].holder||'';state.assets[i]=a}else state.assets.unshift(a);save();state.modal=null;toast('Asset saved');render()}window.saveAsset=saveAsset;
function deleteAsset(id){if(!confirm('Delete this asset record?'))return;state.assets=state.assets.filter(a=>a.id!==decodeURIComponent(id));save();state.modal=null;toast('Asset deleted');render()}window.deleteAsset=deleteAsset;
function quickToggle(id){const a=find(id);if(!a)return;a.availability=a.availability==='CHECKED OUT'?'AVAILABLE':'CHECKED OUT';if(a.availability==='AVAILABLE'){a.project='';a.holder=''}state.transactions.push({time:new Date().toISOString(),assetId:a.id,action:a.availability==='AVAILABLE'?'CHECK IN':'CHECK OUT',holder:a.holder||'',project:a.project||'',location:a.location||'',notes:'Quick action'});save();state.modal=null;toast('Movement recorded');render()}window.quickToggle=quickToggle;
function processMove(){const id=val('moveId'),action=val('moveAction'),a=state.assets.find(x=>x.id.toLowerCase()===id.toLowerCase());if(!a)return toast('Asset ID not found',true);const isOut=action==='CHECK OUT';a.availability=isOut?'CHECKED OUT':'AVAILABLE';a.holder=isOut?val('moveHolder'):'';a.project=isOut?val('moveProject'):'';if(val('moveLocation'))a.location=val('moveLocation');state.transactions.push({time:new Date().toISOString(),assetId:a.id,action,holder:val('moveHolder'),project:val('moveProject'),location:val('moveLocation'),notes:val('moveNotes')});save();toast(`${a.id} ${isOut?'checked out':'checked in'}`);render()}window.processMove=processMove;
function openProject(){state.modal={type:'project'};render()}window.openProject=openProject;function saveProject(){if(!val('p_name'))return toast('Project name is required',true);state.projects.push({name:val('p_name'),production:val('p_production'),location:val('p_location'),status:val('p_status')});save();state.modal=null;toast('Project created');render()}window.saveProject=saveProject;
function toast(msg,bad=false){state.toast={msg,bad};render();setTimeout(()=>{state.toast=null;render()},2400)}
function parseCSV(text){const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){field+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(x=>x.trim()))rows.push(row);row=[];field=''}else field+=c}if(field||row.length){row.push(field);rows.push(row)}return rows}
function normal(s){return s.toLowerCase().replace(/[^a-z0-9]/g,'')}
function mapCsv(text){const rows=parseCSV(text);if(rows.length<2)throw new Error('CSV contains no data');const heads=rows[0].map(normal);const idx=(...names)=>{for(const n of names){const i=heads.indexOf(normal(n));if(i>-1)return i}return -1};const get=(r,...n)=>{const i=idx(...n);return i>-1?(r[i]||'').trim():''};return rows.slice(1).filter(r=>r.some(x=>x.trim())).map(r=>({id:get(r,'ASSET ID (Barcode/SN)','ASSET ID','Barcode','Serial Number'),category:get(r,'CATERGORY','CATEGORY'),equipment:get(r,'EQUIPMENT'),manufacturer:get(r,'MANUFACTURER'),tag:get(r,'COMPANY TAG / MARKING','COMPANY TAG','MARKING'),wll:get(r,'SWL /WLL','SWL / WLL','SWL','WLL'),enteredService:get(r,'ENTERED SERVICE <2026','ENTERED SERVICE'),interval:get(r,'INSPECTION INTERVAL'),lastInspection:parseDate(get(r,'LAST INSPECTION')),inspectedBy:get(r,'INSPECTED BY'),nextInspection:parseDate(get(r,'NEXT INSPECTION')),status:(get(r,'CURRENT STATUS')||'ACTIVE').toUpperCase(),location:get(r,'LOCATION')||'Main Store',availability:(get(r,'AVAILABILITY')||'AVAILABLE').toUpperCase()})).filter(a=>a.id||a.equipment)}
function parseDate(v){if(!v||v==='> Jan 2026'||/n\/a/i.test(v))return '';const d=new Date(v);return isNaN(d)?v:d.toISOString().slice(0,10)}
async function syncSheet(){const url=val('sheetUrl');if(!url)return toast('Enter a published CSV URL',true);try{const res=await fetch(url);if(!res.ok)throw new Error(`HTTP ${res.status}`);const assets=mapCsv(await res.text());if(!assets.length)throw new Error('No asset rows recognised');state.assets=assets;state.sheetUrl=url;localStorage.setItem('asi_sheet_url',url);save();toast(`Synced ${assets.length} assets`);state.view='inventory';render()}catch(e){toast('Sync failed: '+e.message,true)}}window.syncSheet=syncSheet;
function importCsvFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const assets=mapCsv(r.result);if(!assets.length)throw new Error('No recognised rows');state.assets=assets;save();toast(`Imported ${assets.length} assets`);state.view='inventory';render()}catch(e){toast(e.message,true)}};r.readAsText(file)}window.importCsvFile=importCsvFile;
function csvEscape(v){v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
function downloadCsv(name,rows){const blob=new Blob([rows.map(r=>r.map(csvEscape).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportCsv(){const h=['ASSET ID (Barcode/SN)','CATEGORY','EQUIPMENT','MANUFACTURER','COMPANY TAG / MARKING','SWL / WLL','ENTERED SERVICE','INSPECTION INTERVAL','LAST INSPECTION','INSPECTED BY','NEXT INSPECTION','CURRENT STATUS','LOCATION','AVAILABILITY','PROJECT','HOLDER'];downloadCsv('allstunts_inventory.csv',[h,...state.assets.map(a=>[a.id,a.category,a.equipment,a.manufacturer,a.tag,a.wll,a.enteredService,a.interval,a.lastInspection,a.inspectedBy,a.nextInspection,a.status,a.location,a.availability,a.project,a.holder])])}window.exportCsv=exportCsv;
function exportInspectionCsv(){downloadCsv('allstunts_inspections.csv',[['Asset ID','Equipment','Last inspection','Inspector','Interval','Next inspection','Condition'],...state.assets.map(a=>[a.id,a.equipment,a.lastInspection,a.inspectedBy,a.interval,a.nextInspection,inspectionState(a)])])}window.exportInspectionCsv=exportInspectionCsv;
function resetDemo(){if(!confirm('Replace local inventory with the demonstration records?'))return;state.assets=JSON.parse(JSON.stringify(seedAssets));state.transactions=[];save();toast('Demo data restored');render()}window.resetDemo=resetDemo;
render();
