const menu=document.querySelector('.menu-btn'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.credit-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.target).classList.add('active')}));document.querySelectorAll('.section-head,.service-grid article,.feature-copy,.nav-copy,.credit-list,.video-grid,.about-copy').forEach(el=>el.classList.add('reveal'));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));document.getElementById('contactForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const subject=encodeURIComponent(`Website enquiry — ${d.get('service')} — ${d.get('production')||'Production not specified'}`);const body=encodeURIComponent(`Name: ${d.get('name')}\nEmail: ${d.get('email')}\nProduction / company: ${d.get('production')||'Not specified'}\nService: ${d.get('service')}\n\nSequence / enquiry:\n${d.get('message')}`);window.location.href=`mailto:winchesandwirecams@gmail.com?subject=${subject}&body=${body}`;document.getElementById('formNote').textContent='Your email application should now open with the enquiry completed.'});

const videoModal=document.getElementById('videoModal');
const videoFrame=videoModal?.querySelector('iframe');
const closeVideo=()=>{if(!videoModal)return;videoModal.classList.remove('open');videoModal.setAttribute('aria-hidden','true');videoFrame.src='';document.body.style.overflow=''};
document.querySelectorAll('.video-launch').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.video;if(!id||!videoModal)return;videoFrame.src=`https://www.youtube-nocookie.com/embed/${id}?autoplay=1&rel=0`;videoModal.classList.add('open');videoModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';videoModal.querySelector('.video-close').focus()}));
videoModal?.querySelector('.video-close').addEventListener('click',closeVideo);
videoModal?.addEventListener('click',event=>{if(event.target===videoModal)closeVideo()});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeVideo()});
